

#define INVALID_ARGS_NUM "Invalid number of arguments" 
#define FILE_OPEN "Can't open file:" 
#define ALLOCATION_ERROR "Allocation failure" 
#define PRINT_SYM_TABLE "Printing the symbol table:"
#define PRINT_EXT_TABLE "Printing the external table:"
#define ALREADY_INITIALIZED_LABEL "Label already initialized"
#define CANT_ADD_TO_SYMTABLE "Can't add label to symbol table"
#define CANT_ADD_TO_EXTTABLE "Can't add external to external table"
#define INVALID_INSTRUCTION "Invalid instruction"
#define UNKNOWN_OPERAND "Unknown operand"
#define NUMBER_REPRESENTATION_EXCEEDED_12BIN "Number exceeded 12bin representation"
#define INVALID_LABEL_DIRECTIVE "Invalid label directive"
#define INVALID_OPERAND "Invalid operand for the operation"
#define TOO_MANY_OPERANDS "Too Many operands for the operation"
#define MISSING_OPERANDS "Missing an operand for the operation"
#define CANT_ADD_TO_DATA_IMAGE "Can't add a new image entry into data image"
#define TEXT_AFTER_END_OF_STR_NOT_RELEVANT "The text after the second double quote will note be taken into consideration"
#define CANT_FIND_STRING "Unable to find the begining or end of the string"
#define CANT_FIND_SYMBOL "Symbol doesn't exist in symbol table"
#define CANT_CHANGE_LOCATION "can't change Symbol location"
#define INVALID_LIST_DATA "Invalid list of data"
#define INVALID_LABEL_NAME "Invalid label name"
#define PRINT_INSTRUCTION_TABLE "Printing instruction table :"
#define PRINT_CODE_IMAGE "Printing data table :"
#define LINE_NOT_UNDERSTANDABLE "Unable to assemble this line"
#define TOO_MANY_WORDS "too many words. maximum is 4096"
